

name: Gh-Runner setup


on: [push]

jobs:
  ip-10-0-0-249-1:
    timeout-minutes: 10
    name: Remove label on ip-10-0-0-249-1
    runs-on: ip-10-0-0-249
    steps:
    - name: echo
      run: echo "ip-10-0-0-249"
    - name: sleep
      run: sleep 10s 
  ip-10-0-0-249-2:
    timeout-minutes: 10
    name: Remove label on ip-10-0-0-249-2
    runs-on: ip-10-0-0-249
    needs: ip-10-0-0-249-1
    steps:
    - name: echo
      run: echo "ip-10-0-0-249-2"
    - name: sleep
      run: sleep 10s
    - name: docker prune
      run: sudo docker system prune -a -f --volumes
  ip-10-0-0-105-1:
    timeout-minutes: 10
    name: Remove label on ip-10-0-0-105-1
    needs: ip-10-0-0-249-2
    runs-on: ip-10-0-0-105
    steps:
    - name: echo
      run: echo "ip-10-0-0-105-2"
    - name: sleep
      run: sleep 10s
  ip-10-0-0-105-2:
    timeout-minutes: 10
    name: ip-10-0-0-105-2
    runs-on: ip-10-0-0-105
    needs: ip-10-0-0-105-1
    steps:
    - name: echo
      run: echo "ip-10-0-0-105-2"
    - name: sleep
      run: sleep 10s
    - name: docker prune
      run: sudo docker system prune -a -f --volumes
  # clean_ip-10-0-0-249-1:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-249-1
  #   runs-on: ip-10-0-0-249
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-249"
  #   - name: sleep
  #     run: sleep 50s
  #   - name: sleep
  #     run: sleep 50s
  # clean_ip-10-0-0-249-2:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-249-2
  #   runs-on: ip-10-0-0-249
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-249"
  #   - name: sleep
  #     run: sleep 50s
  #   - name: sleep
  #     run: sleep 50s
  # clean_ip-10-0-0-105-1:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-105-1
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-105"
  #   - name: sleep
  #     run: sleep 50s
  #   - name: sleep
  #     run: sleep 50s
  # clean_ip-10-0-0-105-2:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-105-2
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-105"
  #   - name: sleep
  #     run: sleep 50s
  #   - name: sleep
  #     run: sleep 50s
