

name: Gh-Runner setup


on: [push]

jobs:
  ip-10-0-0-249-1:
    timeout-minutes: 10
    name: Remove label on ip-10-0-0-249-1
    runs-on: ip-10-0-0-249
    steps:
    - name: echo
      run: |
         machinename=$(echo ${{ runner.name }} | rev | cut -c 3- | rev)
         echo $machinename
         RUNNER_1_ID=$(curl -L   -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/Pradeep0316/actions/runners | jq '.runners | map(select(.name == "$machinename-1")) | .[].id')
         echo $RUNNER_1_ID
  #   - name: sleep
  #     run: sleep 25s
  # ip-10-0-0-249-2:
  #   timeout-minutes: 10
  #   name: Remove label on ip-10-0-0-249-2
  #   runs-on: ip-10-0-0-249
  #   steps:
  #   - name: echo
  #     run: echo "ip-10-0-0-249-2"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: docker prune
  #     run: sudo docker system prune -a -f --volumes
  # ip-10-0-0-105-1:
  #   timeout-minutes: 10
  #   name: Remove label on ip-10-0-0-105-1
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "ip-10-0-0-105-2"
  #   - name: sleep
  #     run: sleep 25s
  # ip-10-0-0-105-2:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-105-2
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "ip-10-0-0-105-2"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: docker prune
  #     run: sudo docker system prune -a -f --volumes
  # clean_ip-10-0-0-249-1:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-249-1
  #   runs-on: ip-10-0-0-249
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-249"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: sleep
  #     run: sleep 25s
  # clean_ip-10-0-0-249-2:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-249-2
  #   runs-on: ip-10-0-0-249
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-249"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: sleep
  #     run: sleep 25s
  # clean_ip-10-0-0-105-1:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-105-1
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-105"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: sleep
  #     run: sleep 25s
  # clean_ip-10-0-0-105-2:
  #   timeout-minutes: 10
  #   name: ip-10-0-0-105-2
  #   runs-on: ip-10-0-0-105
  #   steps:
  #   - name: echo
  #     run: echo "hello world - ip-10-0-0-105"
  #   - name: sleep
  #     run: sleep 25s
  #   - name: sleep
  #     run: sleep 25s
